---
title: "Sampling"
output: html_document
---

```{r}
init_data <- function (g, a, b, init_k = 20) {
  # a <- 0
  # b <- 1
  # init_k <- 200
  
  h <- function (x) {
    return(log(g(x)))
  }
  
  # abscissa, arrays of data, excluding uppper and lower bound a, b
  
  x <- init_abscissa(h, a, b, init_k = 20)
  
  if (a != -Inf && b != Inf) {
    x <- seq(a, b, length.out = init_k)[2:(init_k-1)]
  }
  
  gx <- sapply(x, g)
  hx <- sapply(x, h)
  dhx <- grad(h, x)
  
  k <- length(x)
  
  # calculate zs' using formula (1)
  # 2:k -- j+1,  1:k-1 -- j
  z <- (hx[2:k] - hx[1:k-1] - x[2:k] * dhx[2:k] + x[1:k-1] * dhx[1:k-1]) / (dhx[1:k-1] - dhx[2:k])
    
  # z's index start from 0, ends with k, i.e., z[1] represents z_0, z[k+1] represents z_k
  z <- c(a, z, b)
  data <- list(x = x, hx = hx, dhx = dhx, z = z, k = length(x), a = a, b = b)
  return(data) 
}

init_abscissa <- function(h, a, b, init_k = 20) {
  
  # both finite
  if (a != -Inf && b != Inf){
    return(seq(a, b, length.out = init_k+2)[2:(init_k+1)])
  }
  
  # if infinite on left side, find x_0, s.t. dhx_0 > 0
  if (a == -Inf){
    x_0 <- -10
    while (grad(h, x_0) <= 0){
      x_0 <- x_0 * 2
    }
  }
  # else set a finite left bound
  else {
    x_0 = a + 1
  }
  
  # similarly if infinte on right side
  if (b == Inf){
    x_k <- 10
    while (grad(h, x_k) >= 0){
      x_k <- x_k * 2
    }
  }
  else {
    x_k = b - 1
  }
  
  x <- seq(x_0, x_k, length.out = init_k)
  
  return(x)
}

# x_value
uk <- function (x_value, data) {
  # x_value in [z_{j-1}, z_{j}]
  j <- sum(x_value > data$z) 
  # boundary cases
  if (x_value == data$a){
    j = 1
  }
  if (x_value == data$b){
    j = data$k
  }
  
  # calculating with equation (2)
  result <- data$hx[j] + (x_value - data$x[j]) * data$dhx[j]
  
  return(result)
}

lk <- function (x_value, data = data) {
  # x_value in [x_{j}, x{j+1}]
  j <- sum(x_value > data$x)
  
  if (j == 0 || j == data$k) {
    result <- -Inf
  }
  else {
    # calculating with equation (4)
    result <- ((data$x[j+1] - x_value) * data$hx[j] + (x_value - data$x[j]) * data$hx[j+1] )/
      (data$x[j+1] - data$x[j])
  }
  return(result)
}

update_data <- function (data, new_data) {
  # combining data and sorting
  combined_x <- c(data$x, new_data$x)
  combined_hx <- c(data$x, new_data$hx)
  combined_dhx <- c(data$x, new_data$dhx)
  
  sort_order <- order(combined_x)
  
  # new arrays
  x <- combined_x[sort_order]
  hx <- combined_hx[sort_order]
  dhx <- combined_dhx[sort_order]
  
  k <- length(x)
  data$k <- k
  
  # recalculate z after sorting
  z <- (hx[2:k] - hx[1:k-1] - x[2:k] * dhx[2:k] + x[1:k-1] * dhx[1:k-1]) / (dhx[1:k-1] - dhx[2:k])
  z <- c(data$a, z, data$b)
  
  data <- list(x = x, hx = hx, dhx = dhx, z = z, k = k, a = a, b = b)
  return(data)
}

```


```{r}

# The function exp_sampling takes in a our data structure corresponding to 
# the x_i, hx_i and d_h_xi
# exp_sampling will return an array of x_j
exp_sampling = function(n, x_list) {
  
  # Grab the number of rows
  k = x_list$k
  
  # Save the intersection points of our upper hull
  intersections = x_list$z
  
  # First sample from a multinomial with probabilities corresponding to 
  # the area under each piece of the adjusted piecewise upper hull
  
  # Get the area under the curve for each section
  # Maybe we should switch to the integrate function here
  upper = sapply(x_list$x, uk, data=x_list)
  
  probabilities = abs(diff(exp(upper)/x_list$dhx))
  sum_prob = sum(probabilities)
  prob_vector = probabilities / sum_prob
  
  
  # Sample and return a vector of indexes
  sample_multinom = rmultinom(n, 1, prob_vector)
  
  i_vector = colSums(sample_multinom*(1:(k-1)))
  
  # Next let's draw n uniform variables
  unif_draws = runif(n)
  slope_j = x_list$dhx[i_vector]
  z_j = intersections[i_vector]
  constant_j = slope_j*z_j + upper[i_vector]
  
  prob_indexed = prob_vector[i_vector]
  
  print('sample')
  sample = log(exp(slope_j*z_j) + 
            sum_prob*slope_j*prob_indexed*exp(-constant_j)*unif_draws) / slope_j
  
  print('return')
  return(sample)

  
}
```


```{r}

# The rejection step will take in a sample vector, a matrix of the points 
# that have already been sampled, and the function that we are trying to sample
rejection_step = function(sample_vector, x_list, f_x) {
  
  # Find upper and lower shell functions
  
  lower_shell = sapply(sample_vector, lk, data=x_list)
  upper_shell = sapply(sample_vector, uk, data=x_list)
  
  # Uniform Sample
  unif_w = runif(n = length(sample_vector))
  
  # Squeezing step
  
  log_vec = unif_w <= exp(lower_shell - upper_shell)
  
  # Rejection step
  rejection_step_log_vec = unif_w[!log_vec] <= 
                            exp(log(f_x(sample_vector[!log_vec])) - 
                               upper_shell[!log_vec])
  
  log_vec[which(!log_vec)] = rejection_step_log_vec
  
  # Return accepted values
  return(sample_vector[log_vec])
  
}

```


Test with the x^2 function
```{r}
g <- function (x) {
  return(x^2)
}

h <- function (x) {
  return(log(g(x)))
}

data <- init_data(g, -2, 2)

uk(1.1, data)
lk(1.1, data)
```


```{r}
hist(exp_sampling(10000, data), breaks = 20)
```

```{r}
hist(rejection_step(exp_sampling(10000, data), data, g), breaks = 20)
```


```{r}
g2 <- function (x) {
  return(dnorm(x))
}

h2 <- function(x) {
  return(log(g2(x)))
}

init_abscissa(h2, -Inf, Inf)
data2 <- init_data(g2, -Inf, Inf)
```


```{r}
exp_sampling(1000, data2)
```

```{r}
hist(rejection_step(exp_sampling(100, data2), data2, g2), breaks = 20)
```

```{r}
set.seed(1)
exp_sampling(1000, data2)
```






